# Generated by Django 4.2.1 on 2023-06-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default/default.jpg', null=True, upload_to='profile_pic/'),
        ),
    ]
